testing-host-1:
  hostname:
  user: skrum-user
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/funengage_id_rsa
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: testing
  roles:
    - app
    - db
  deploy_path: /usr/share/nginx/html

staging-host-1:
  hostname: 
  user: skrum-user
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/funengage_id_rsa
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: staging
  roles:
    - app
    - db
  deploy_path: /usr/share/nginx/html

production-host-1:
  hostname: 
  user: skrum-user
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/funengage_id_rsa
  forwardAgent: true
  multiplexing: false
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - app
    - db
  deploy_path: /usr/share/nginx/html
  branch: master
